FROM golang:1.18-alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

# copy source files

RUN go get ./...
RUN go run cmd/main.go local



FROM node:alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

# copy source files
COPY . /usr/src

# install dependencies
RUN yarn install

# start app
RUN yarn build
EXPOSE 3000
CMD yarn start